#!/bin/sh 
# $Id: miniupnpd.init.d.script,v 1.3 2012/03/14 22:09:53 nanard Exp $
# MiniUPnP project
# author: Thomas Bernard
# website: http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/


UPNP_MODE=`uci get lte-gw.nat.upnp_mode 2> /dev/null`
if [ $? -ne 0 ];
then
     echo "didnt find upnp in uci" > /dev/kmsg
     exit 0
fi

if [ $UPNP_MODE == "disable" ]
then
        echo "UPnP disabled" > /dev/kmsg
        exit 0
fi

EXE="/usr/local/bin/upnp.sh"

case "$1" in
  start)
    `$EXE start`
        ;;
  stop)
    `$EXE stop`
        ;;
  restart|reload|force-reload)
        `$EXE restart`
        ;;
  *)
        echo "Usage: /etc/init.d/S99upnp {start|stop|restart|reload|force-reload} wan_if (lte0.1 ...)"
        exit 2
        ;;
esac
exit 0
